//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.cl
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="Facturacion.cl.wsplanoSoap")]
    public interface wsplanoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Procesar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.ProcesarResponse Procesar(Facturacion.cl.ProcesarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Procesar", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.ProcesarResponse> ProcesarAsync(Facturacion.cl.ProcesarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.ObtenerLinkResponse ObtenerLink(Facturacion.cl.ObtenerLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerLink", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.ObtenerLinkResponse> ObtenerLinkAsync(Facturacion.cl.ObtenerLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoletaTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.getBoletaTicketResponse getBoletaTicket(Facturacion.cl.getBoletaTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoletaTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.getBoletaTicketResponse> getBoletaTicketAsync(Facturacion.cl.getBoletaTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getXMLDte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.getXMLDteResponse getXMLDte(Facturacion.cl.getXMLDteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getXMLDte", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.getXMLDteResponse> getXMLDteAsync(Facturacion.cl.getXMLDteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.AltNumResponse AltNum(Facturacion.cl.AltNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.AltNumResponse> AltNumAsync(Facturacion.cl.AltNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.RegIPResponse RegIP(Facturacion.cl.RegIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegIP", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.RegIPResponse> RegIPAsync(Facturacion.cl.RegIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.getIPResponse getIP(Facturacion.cl.getIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIP", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.getIPResponse> getIPAsync(Facturacion.cl.getIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.EliminarDocResponse EliminarDoc(Facturacion.cl.EliminarDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.EliminarDocResponse> EliminarDocAsync(Facturacion.cl.EliminarDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnularGuia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.AnularGuiaResponse AnularGuia(Facturacion.cl.AnularGuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnularGuia", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.AnularGuiaResponse> AnularGuiaAsync(Facturacion.cl.AnularGuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Online", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.OnlineResponse Online(Facturacion.cl.OnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Online", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.OnlineResponse> OnlineAsync(Facturacion.cl.OnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Version", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.VersionResponse Version(Facturacion.cl.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Version", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.VersionResponse> VersionAsync(Facturacion.cl.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarWSMasivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.ProcesarWSMasivoResponse ProcesarWSMasivo(Facturacion.cl.ProcesarWSMasivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarWSMasivo", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.ProcesarWSMasivoResponse> ProcesarWSMasivoAsync(Facturacion.cl.ProcesarWSMasivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.ConsultarEstadoResponse ConsultarEstado(Facturacion.cl.ConsultarEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.ConsultarEstadoResponse> ConsultarEstadoAsync(Facturacion.cl.ConsultarEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaLibroVentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.ConsultaLibroVentasResponse ConsultaLibroVentas(Facturacion.cl.ConsultaLibroVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaLibroVentas", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.ConsultaLibroVentasResponse> ConsultaLibroVentasAsync(Facturacion.cl.ConsultaLibroVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LibroVentasDetallado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.cl.LibroVentasDetalladoResponse LibroVentasDetallado(Facturacion.cl.LibroVentasDetalladoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LibroVentasDetallado", ReplyAction="*")]
        System.Threading.Tasks.Task<Facturacion.cl.LibroVentasDetalladoResponse> LibroVentasDetalladoAsync(Facturacion.cl.LibroVentasDetalladoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class logininfo
    {
        
        private string usuarioField;
        
        private string rutField;
        
        private string claveField;
        
        private string puertoField;
        
        private string incluyeLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut
        {
            get
            {
                return this.rutField;
            }
            set
            {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Puerto
        {
            get
            {
                return this.puertoField;
            }
            set
            {
                this.puertoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IncluyeLink
        {
            get
            {
                return this.incluyeLinkField;
            }
            set
            {
                this.incluyeLinkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Procesar", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ProcesarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public int formato;
        
        public ProcesarRequest()
        {
        }
        
        public ProcesarRequest(Facturacion.cl.logininfo login, string file, int formato)
        {
            this.login = login;
            this.file = file;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ProcesarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string ProcesarResult;
        
        public ProcesarResponse()
        {
        }
        
        public ProcesarResponse(string ProcesarResult)
        {
            this.ProcesarResult = ProcesarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerLink", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ObtenerLinkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string tpomov;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string cedible;
        
        public ObtenerLinkRequest()
        {
        }
        
        public ObtenerLinkRequest(Facturacion.cl.logininfo login, string tpomov, string folio, string tipo, string cedible)
        {
            this.login = login;
            this.tpomov = tpomov;
            this.folio = folio;
            this.tipo = tipo;
            this.cedible = cedible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerLinkResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ObtenerLinkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string ObtenerLinkResult;
        
        public ObtenerLinkResponse()
        {
        }
        
        public ObtenerLinkResponse(string ObtenerLinkResult)
        {
            this.ObtenerLinkResult = ObtenerLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBoletaTicket", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getBoletaTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string ticket;
        
        public getBoletaTicketRequest()
        {
        }
        
        public getBoletaTicketRequest(Facturacion.cl.logininfo login, string ticket)
        {
            this.login = login;
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBoletaTicketResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getBoletaTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string getBoletaTicketResult;
        
        public getBoletaTicketResponse()
        {
        }
        
        public getBoletaTicketResponse(string getBoletaTicketResult)
        {
            this.getBoletaTicketResult = getBoletaTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLDte", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getXMLDteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string tpomov;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string tipo;
        
        public getXMLDteRequest()
        {
        }
        
        public getXMLDteRequest(Facturacion.cl.logininfo login, string tpomov, string folio, string tipo)
        {
            this.login = login;
            this.tpomov = tpomov;
            this.folio = folio;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLDteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getXMLDteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getXMLDteResult;
        
        public getXMLDteResponse()
        {
        }
        
        public getXMLDteResponse(byte[] getXMLDteResult)
        {
            this.getXMLDteResult = getXMLDteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AltNum", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AltNumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string campo;
        
        public AltNumRequest()
        {
        }
        
        public AltNumRequest(Facturacion.cl.logininfo login, string folio, string tipo, string campo)
        {
            this.login = login;
            this.folio = folio;
            this.tipo = tipo;
            this.campo = campo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AltNumResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AltNumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string AltNumResult;
        
        public AltNumResponse()
        {
        }
        
        public AltNumResponse(string AltNumResult)
        {
            this.AltNumResult = AltNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegIP", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class RegIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string puerto;
        
        public RegIPRequest()
        {
        }
        
        public RegIPRequest(Facturacion.cl.logininfo login, string puerto)
        {
            this.login = login;
            this.puerto = puerto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegIPResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class RegIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string RegIPResult;
        
        public RegIPResponse()
        {
        }
        
        public RegIPResponse(string RegIPResult)
        {
            this.RegIPResult = RegIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIP", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getIPRequest
    {
        
        public getIPRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIPResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string getIPResult;
        
        public getIPResponse()
        {
        }
        
        public getIPResponse(string getIPResult)
        {
            this.getIPResult = getIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDoc", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class EliminarDocRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string tpomov;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string tipo;
        
        public EliminarDocRequest()
        {
        }
        
        public EliminarDocRequest(Facturacion.cl.logininfo login, string tpomov, string folio, string tipo)
        {
            this.login = login;
            this.tpomov = tpomov;
            this.folio = folio;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDocResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class EliminarDocResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string EliminarDocResult;
        
        public EliminarDocResponse()
        {
        }
        
        public EliminarDocResponse(string EliminarDocResult)
        {
            this.EliminarDocResult = EliminarDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnularGuia", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AnularGuiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string tpomov;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string tipo;
        
        public AnularGuiaRequest()
        {
        }
        
        public AnularGuiaRequest(Facturacion.cl.logininfo login, string tpomov, string folio, string tipo)
        {
            this.login = login;
            this.tpomov = tpomov;
            this.folio = folio;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnularGuiaResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class AnularGuiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string AnularGuiaResult;
        
        public AnularGuiaResponse()
        {
        }
        
        public AnularGuiaResponse(string AnularGuiaResult)
        {
            this.AnularGuiaResult = AnularGuiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Online", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class OnlineRequest
    {
        
        public OnlineRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class OnlineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string OnlineResult;
        
        public OnlineResponse()
        {
        }
        
        public OnlineResponse(string OnlineResult)
        {
            this.OnlineResult = OnlineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Version", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class VersionRequest
    {
        
        public VersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VersionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class VersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string VersionResult;
        
        public VersionResponse()
        {
        }
        
        public VersionResponse(string VersionResult)
        {
            this.VersionResult = VersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarWSMasivo", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ProcesarWSMasivoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public int formato;
        
        public ProcesarWSMasivoRequest()
        {
        }
        
        public ProcesarWSMasivoRequest(Facturacion.cl.logininfo login, string file, int formato)
        {
            this.login = login;
            this.file = file;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarWSMasivoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ProcesarWSMasivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string ProcesarWSMasivoResult;
        
        public ProcesarWSMasivoResponse()
        {
        }
        
        public ProcesarWSMasivoResponse(string ProcesarWSMasivoResult)
        {
            this.ProcesarWSMasivoResult = ProcesarWSMasivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarEstado", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ConsultarEstadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public int trackid;
        
        public ConsultarEstadoRequest()
        {
        }
        
        public ConsultarEstadoRequest(Facturacion.cl.logininfo login, int trackid)
        {
            this.login = login;
            this.trackid = trackid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarEstadoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ConsultarEstadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string ConsultarEstadoResult;
        
        public ConsultarEstadoResponse()
        {
        }
        
        public ConsultarEstadoResponse(string ConsultarEstadoResult)
        {
            this.ConsultarEstadoResult = ConsultarEstadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLibroVentas", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ConsultaLibroVentasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string fechadocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string tipolibro;
        
        public ConsultaLibroVentasRequest()
        {
        }
        
        public ConsultaLibroVentasRequest(Facturacion.cl.logininfo login, string fechadocumento, string tipolibro)
        {
            this.login = login;
            this.fechadocumento = fechadocumento;
            this.tipolibro = tipolibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLibroVentasResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ConsultaLibroVentasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string ConsultaLibroVentasResult;
        
        public ConsultaLibroVentasResponse()
        {
        }
        
        public ConsultaLibroVentasResponse(string ConsultaLibroVentasResult)
        {
            this.ConsultaLibroVentasResult = ConsultaLibroVentasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibroVentasDetallado", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class LibroVentasDetalladoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Facturacion.cl.logininfo login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string fechadocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string tipolibro;
        
        public LibroVentasDetalladoRequest()
        {
        }
        
        public LibroVentasDetalladoRequest(Facturacion.cl.logininfo login, string fechadocumento, string tipolibro)
        {
            this.login = login;
            this.fechadocumento = fechadocumento;
            this.tipolibro = tipolibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibroVentasDetalladoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class LibroVentasDetalladoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string LibroVentasDetalladoResult;
        
        public LibroVentasDetalladoResponse()
        {
        }
        
        public LibroVentasDetalladoResponse(string LibroVentasDetalladoResult)
        {
            this.LibroVentasDetalladoResult = LibroVentasDetalladoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface wsplanoSoapChannel : Facturacion.cl.wsplanoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class wsplanoSoapClient : System.ServiceModel.ClientBase<Facturacion.cl.wsplanoSoap>, Facturacion.cl.wsplanoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsplanoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsplanoSoapClient.GetBindingForEndpoint(endpointConfiguration), wsplanoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsplanoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsplanoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsplanoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsplanoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsplanoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public wsplanoSoapClient()
        {
        }

        public Facturacion.cl.ProcesarResponse Procesar(Facturacion.cl.ProcesarRequest request)
        {
            return base.Channel.Procesar(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.ProcesarResponse> ProcesarAsync(Facturacion.cl.ProcesarRequest request)
        {
            return base.Channel.ProcesarAsync(request);
        }
        
        public Facturacion.cl.ObtenerLinkResponse ObtenerLink(Facturacion.cl.ObtenerLinkRequest request)
        {
            return base.Channel.ObtenerLink(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.ObtenerLinkResponse> ObtenerLinkAsync(Facturacion.cl.ObtenerLinkRequest request)
        {
            return base.Channel.ObtenerLinkAsync(request);
        }
        
        public Facturacion.cl.getBoletaTicketResponse getBoletaTicket(Facturacion.cl.getBoletaTicketRequest request)
        {
            return base.Channel.getBoletaTicket(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.getBoletaTicketResponse> getBoletaTicketAsync(Facturacion.cl.getBoletaTicketRequest request)
        {
            return base.Channel.getBoletaTicketAsync(request);
        }
        
        public Facturacion.cl.getXMLDteResponse getXMLDte(Facturacion.cl.getXMLDteRequest request)
        {
            return base.Channel.getXMLDte(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.getXMLDteResponse> getXMLDteAsync(Facturacion.cl.getXMLDteRequest request)
        {
            return base.Channel.getXMLDteAsync(request);
        }
        
        public Facturacion.cl.AltNumResponse AltNum(Facturacion.cl.AltNumRequest request)
        {
            return base.Channel.AltNum(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.AltNumResponse> AltNumAsync(Facturacion.cl.AltNumRequest request)
        {
            return base.Channel.AltNumAsync(request);
        }
        
        public Facturacion.cl.RegIPResponse RegIP(Facturacion.cl.RegIPRequest request)
        {
            return base.Channel.RegIP(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.RegIPResponse> RegIPAsync(Facturacion.cl.RegIPRequest request)
        {
            return base.Channel.RegIPAsync(request);
        }
        
        public Facturacion.cl.getIPResponse getIP(Facturacion.cl.getIPRequest request)
        {
            return base.Channel.getIP(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.getIPResponse> getIPAsync(Facturacion.cl.getIPRequest request)
        {
            return base.Channel.getIPAsync(request);
        }
        
        public Facturacion.cl.EliminarDocResponse EliminarDoc(Facturacion.cl.EliminarDocRequest request)
        {
            return base.Channel.EliminarDoc(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.EliminarDocResponse> EliminarDocAsync(Facturacion.cl.EliminarDocRequest request)
        {
            return base.Channel.EliminarDocAsync(request);
        }
        
        public Facturacion.cl.AnularGuiaResponse AnularGuia(Facturacion.cl.AnularGuiaRequest request)
        {
            return base.Channel.AnularGuia(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.AnularGuiaResponse> AnularGuiaAsync(Facturacion.cl.AnularGuiaRequest request)
        {
            return base.Channel.AnularGuiaAsync(request);
        }
        
        public Facturacion.cl.OnlineResponse Online(Facturacion.cl.OnlineRequest request)
        {
            return base.Channel.Online(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.OnlineResponse> OnlineAsync(Facturacion.cl.OnlineRequest request)
        {
            return base.Channel.OnlineAsync(request);
        }
        
        public Facturacion.cl.VersionResponse Version(Facturacion.cl.VersionRequest request)
        {
            return base.Channel.Version(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.VersionResponse> VersionAsync(Facturacion.cl.VersionRequest request)
        {
            return base.Channel.VersionAsync(request);
        }
        
        public Facturacion.cl.ProcesarWSMasivoResponse ProcesarWSMasivo(Facturacion.cl.ProcesarWSMasivoRequest request)
        {
            return base.Channel.ProcesarWSMasivo(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.ProcesarWSMasivoResponse> ProcesarWSMasivoAsync(Facturacion.cl.ProcesarWSMasivoRequest request)
        {
            return base.Channel.ProcesarWSMasivoAsync(request);
        }
        
        public Facturacion.cl.ConsultarEstadoResponse ConsultarEstado(Facturacion.cl.ConsultarEstadoRequest request)
        {
            return base.Channel.ConsultarEstado(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.ConsultarEstadoResponse> ConsultarEstadoAsync(Facturacion.cl.ConsultarEstadoRequest request)
        {
            return base.Channel.ConsultarEstadoAsync(request);
        }
        
        public Facturacion.cl.ConsultaLibroVentasResponse ConsultaLibroVentas(Facturacion.cl.ConsultaLibroVentasRequest request)
        {
            return base.Channel.ConsultaLibroVentas(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.ConsultaLibroVentasResponse> ConsultaLibroVentasAsync(Facturacion.cl.ConsultaLibroVentasRequest request)
        {
            return base.Channel.ConsultaLibroVentasAsync(request);
        }
        
        public Facturacion.cl.LibroVentasDetalladoResponse LibroVentasDetallado(Facturacion.cl.LibroVentasDetalladoRequest request)
        {
            return base.Channel.LibroVentasDetallado(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.cl.LibroVentasDetalladoResponse> LibroVentasDetalladoAsync(Facturacion.cl.LibroVentasDetalladoRequest request)
        {
            return base.Channel.LibroVentasDetalladoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsplanoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsplanoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsplanoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.facturacion.cl/WSDS/wsplano.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsplanoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.facturacion.cl/WSDS/wsplano.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsplanoSoap,
            
            wsplanoSoap12,
        }
    }
}
